name: Build SPDK

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install additional packages
        run: sudo ./scripts/pkgdep.sh
      - name: Configure
        run: |
          ./configure \
              --without-uring \
              --without-fio \
              --without-rbd \
              --without-rdma \
              --without-shared \
              --with-iscsi-initiator \
              --without-vtune \
              --with-vfio-user
      - name: Make
        run: make

      # - name: Compile RPM
      #   run: |
      #     ./rpmbuild/rpm.sh \
      #         --target-arch=${ARCH} \
      #         --without-uring \
      #         --with-crypto \
      #         --without-fio \
      #         --with-raid5f \
      #         --with-vhost \
      #         --without-rbd \
      #         --with-rdma \
      #         --without-shared \
      #         --with-iscsi-initiator \
      #         --without-vtune \
      #         --with-vfio-user
      #   env:
      #     DEPS: no
      #     LDFLAGS: " "
      #     ARCH: x86

      - name: Done
        run: echo done

