name: Build SPDK

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Update submodules
        run: git submodule update --init --depth 1
      - name: Install additional packages
        run: sudo ./scripts/pkgdep.sh
      - name: Compile
        run: |
          ./rpmbuild/rpm.sh \
              --target-arch=${ARCH} \
              --without-uring \
              --with-crypto \
              --without-fio \
              --with-raid5f \
              --with-vhost \
              --without-rbd \
              --with-rdma \
              --without-shared \
              --with-iscsi-initiator \
              --without-vtune \
              --with-vfio-user
        env:
          DEPS: no
          LDFLAGS: " "
          ARCH: x86
      - name: Done
        run: echo done

